apiVersion: v1
kind: Pod
metadata:
  name: nfs-test
  namespace: online-boutique
spec:
  containers:
  - name: test
    image: busybox
    command: ["sleep","3600"]
    volumeMounts:
    - name: shared
      mountPath: /data
  volumes:
  - name: shared
    persistentVolumeClaim:
      claimName: nfs-shared-pvc
