apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-shared-pvc
  namespace: online-boutique
spec:
  volumeName: nfs-shared-pv
  storageClassName: ""
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
